export interface QAItem {
  q: string;
  a: string;
  keywords: string[];
  roles?: ('board_member' | 'member' | 'administrator')[];
  pages?: string[];
  denyRoles?: ('board_member' | 'member' | 'administrator')[];
}

export const knowledgeBase: QAItem[] = [
  // ─── Event Management ───
  {
    q: "How do I create a new event?",
    a: "Go to Dashboard → Events. You'll see an 'Add Event' button at the top. Click it and fill in the event title, date, time, location, description, and image. Click 'Create Event' to save. The event will appear on the public Events page and homepage automatically.",
    keywords: ["create event", "add event", "new event", "schedule event", "event form", "make event", "setup event", "host event", "organize event", "event creation"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],
    pages: ["/dashboard/events"],
  },
  {
    q: "Where do I find the list of events?",
    a: "Go to Dashboard → Events. All events are listed there with their date, time, and status. You can also click the event title to view it on the public page. From this list you can edit or delete events.",
    keywords: ["find events", "event list", "view events", "where are events", "events page", "show events", "event directory", "list of events"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],
    pages: ["/dashboard/events"],
  },
  {
    q: "How do I edit or delete an event?",
    a: "Go to Dashboard → Events. Find the event in the list and click the Edit (pencil) or Delete (trash) icon next to it. Editing lets you change the title, date, time, location, description, or image. Deleting removes it permanently.",
    keywords: ["edit event", "delete event", "modify event", "remove event", "update event", "change event", "cancel event"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],
    pages: ["/dashboard/events"],
  },
  {
    q: "How do I approve or reject RSVPs for an event?",
    a: "Go to Dashboard → Events. Scroll down to the RSVPs section. You'll see Approve (green check) and Reject (red X) buttons next to each pending RSVP. You can also use the 'Approve All' or 'Reject All' buttons to process all pending RSVPs at once.",
    keywords: ["approve rsvp", "reject rsvp", "confirm rsvp", "cancel rsvp", "rsvp pending", "rsvp approval", "manage rsvp", "rsvp list", "rsvp management"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],
    pages: ["/dashboard/events"],
  },

  // ─── Program Management ───
  {
    q: "How do I create a new program?",
    a: "Go to Dashboard → Programs. Click 'Add Program'. Fill in the title, slug (URL name), description, images, stats, and testimonial quote. Click 'Create Program' to save. The program will appear on the Programs page.",
    keywords: ["create program", "add program", "new program", "program form", "make program", "setup program", "program creation", "start program", "launch program"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],    pages: ["/dashboard/programs"],
  },
  {
    q: "Where do I find and edit programs?",
    a: "Go to Dashboard → Programs. All programs are shown in a list with Edit (pencil) and Delete (trash) buttons. Click Edit to change the title, description, images, or any other field. Changes save immediately.",
    keywords: ["find programs", "program list", "edit program", "modify program", "update program", "program page", "view programs", "change program"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],    pages: ["/dashboard/programs"],
  },
  {
    q: "How do I approve or reject program enrollments?",
    a: "Go to Dashboard → Programs. The Enrollments section shows all sign-ups with their status (pending, approved, rejected, completed). Use the Approve (green) or Reject (red) buttons next to pending enrollments, or use 'Approve All' / 'Reject All' to batch process them.",
    keywords: ["approve enrollment", "reject enrollment", "enrollment pending", "program enrollment", "manage enrollment", "enrollment approval", "student enrollment", "sign up approval"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],    pages: ["/dashboard/programs"],
  },
  {
    q: "How do I delete a program?",
    a: "Go to Dashboard → Programs. Find the program you want to remove and click the Delete (trash) icon. Confirm the deletion. This cannot be undone, so make sure the program is no longer needed.",
    keywords: ["delete program", "remove program", "destroy program", "erase program"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],    pages: ["/dashboard/programs"],
  },

  // ─── News Management ───
  {
    q: "How do I add news articles?",
    a: "Go to Dashboard → News. Click 'Add News'. Fill in the title, slug, excerpt (short summary), and content. You can also add an image. Set the published toggle to make it visible on the homepage. Click 'Save'.",
    keywords: ["create news", "add news", "new article", "news article", "publish news", "write news", "post news", "news post", "announcement"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],    pages: ["/dashboard/news"],
  },
  {
    q: "How do I edit or unpublish a news article?",
    a: "Go to Dashboard → News. Find the article and click Edit (pencil) to change its content. Toggle the 'Published' switch off to unpublish (hide from public). You can also delete the article with the Delete (trash) button.",
    keywords: ["edit news", "unpublish news", "delete news", "remove article", "hide news", "news edit", "modify news"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],    pages: ["/dashboard/news"],
  },

  // ─── Testimonial Management ───
  {
    q: "How do I manage testimonials?",
    a: "Go to Dashboard → Testimonials. You can add new testimonials with a person's name, their role, the testimonial text, and select which pages to display it on. Use the Activate/Deactivate buttons to toggle visibility. Use 'Activate All' / 'Deactivate All' for bulk changes.",
    keywords: ["testimonial", "review", "feedback", "activate testimonial", "deactivate testimonial", "add testimonial", "manage review", "community voice"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],    pages: ["/dashboard/testimonials"],
  },

  // ─── Masjid Construction ───
  {
    q: "How do I update masjid construction progress?",
    a: "Go to Dashboard → Construction. You can add updates with images, videos, captions, and phase information. Each update tracks the fundraising progress (raised amount vs goal). Updates appear on the Masjid Construction page.",
    keywords: ["construction update", "masjid progress", "building update", "fundraising progress", "add construction", "construction photo", "building phase", "masjid status"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],    pages: ["/dashboard/construction"],
  },
  {
    q: "How do I add construction photos?",
    a: "Go to Dashboard → Construction. Click 'Add Update'. Upload images showing the latest progress. Add a caption describing what's in the photo. These images appear in the gallery on the public Masjid Construction page.",
    keywords: ["construction photo", "upload image", "add photo", "building picture", "masjid image", "gallery photo"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],    pages: ["/dashboard/construction"],
  },

  // ─── Donations & Pledges ───
  {
    q: "How do I view and manage donations?",
    a: "Go to Dashboard → Donations. Here you can see all donations, add manual donations (cash/check), and export data as CSV. The Pledges section below shows pending pledges that you can mark as fulfilled or cancelled.",
    keywords: ["donation", "pledge", "manual donation", "cash donation", "check donation", "export donations", "donation list", "view donations", "donation management"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],    pages: ["/dashboard/donations"],
  },
  {
    q: "How do I record a cash or check donation?",
    a: "Go to Dashboard → Donations. Click 'Add Manual Donation' to record a cash or check donation. Enter the donor's name, email, amount, and designation (e.g., Masjid Construction, General Fund). This creates a record like any other donation.",
    keywords: ["cash donation", "check donation", "manual donation", "record donation", "offline donation", "add donation"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],    pages: ["/dashboard/donations"],
  },
  {
    q: "How do I manage pledges?",
    a: "Go to Dashboard → Pledges. All pledges are listed with their status (pending/fulfilled/cancelled). Use 'Fulfill' to mark a pledge as completed, or 'Cancel' to void it. Use 'Fulfill All' / 'Cancel All' for bulk actions.",
    keywords: ["pledge", "fulfill pledge", "cancel pledge", "pledge management", "pledge status", "pending pledge", "pledge list", "manage pledge"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],    pages: ["/dashboard/pledges"],
  },

  // ─── Contact & FAQ ───
  {
    q: "How do I handle contact form submissions?",
    a: "Go to Dashboard → Contact & FAQ. Contact submissions are listed with a 'Mark as Read' button. Use 'Mark All Read' to batch process unread submissions. You can also manage FAQs, view volunteer submissions, and reorder FAQ items.",
    keywords: ["contact submission", "contact form", "mark read", "faq", "volunteer submission", "contact inquiry", "message from public", "contact management"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],    pages: ["/dashboard/contact-submissions"],
  },
  {
    q: "How do I manage FAQ questions?",
    a: "Go to Dashboard → Contact & FAQ. Scroll to the FAQ section. You can add new FAQs, edit existing ones, reorder them using the up/down arrows, and toggle them active/inactive. FAQs with 'Active' checked appear on the public FAQ page.",
    keywords: ["faq", "add question", "edit faq", "faq answer", "faq order", "frequently asked", "manage faq", "faq list"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],    pages: ["/dashboard/contact-submissions"],
  },
  {
    q: "How do I view volunteer submissions?",
    a: "Go to Dashboard → Contact & FAQ. Scroll down to the Volunteer Submissions section. You'll see all volunteer sign-ups with their contact info, availability, and interests. You can delete entries that are no longer needed.",
    keywords: ["volunteer", "volunteer submission", "volunteer signup", "volunteer list", "volunteer interest"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],    pages: ["/dashboard/contact-submissions"],
  },

  // ─── User Management ───
  {
    q: "How do I manage users and members?",
    a: "Go to Dashboard → Members. You can see all registered users, their roles (board member or regular member), and their activity (enrollments, RSVPs, pledges, donations). You can delete users if needed.",
    keywords: ["user", "member", "board member", "delete user", "user list", "manage user", "member list", "registered user", "user role"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],    pages: ["/dashboard/users"],
  },

  // ─── Activity Log ───
  {
    q: "How do I view activity logs?",
    a: "Go to Dashboard → Activity Log. This shows all actions taken by board members (creating events, approving RSVPs, etc.). You can revert certain changes if needed using the 'Revert' button.",
    keywords: ["activity log", "audit trail", "history", "revert", "board activity", "action log", "change history", "who did what"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],    pages: ["/dashboard/activity"],
  },

  // ─── Analytics ───
  {
    q: "How do I see analytics and stats?",
    a: "Go to Dashboard → Analytics. This shows charts and cards with key metrics: events, programs, users, donations, enrollments, RSVPs, and more. You can also edit the About page stats (years serving, number of families) from this page.",
    keywords: ["analytics", "statistics", "stats", "metrics", "dashboard stats", "about stats", "data", "charts", "report", "performance"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],    pages: ["/dashboard/analytics"],
  },

  // ─── Scheduling Requests ───
  {
    q: "How do I manage scheduling requests?",
    a: "Go to Dashboard → Scheduling. Event scheduling requests from the public appear here with details about their event. Use Approve (green) or Reject (red) buttons per request, or use 'Approve All' / 'Reject All' for bulk processing.",
    keywords: ["scheduling request", "event request", "approve scheduling", "reject scheduling", "facility request", "room booking", "calendar request"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],    pages: ["/dashboard/scheduling"],
  },

  // ─── Invite Codes ───
  {
    q: "How do I create an invite code for new board members?",
    a: "Go to Dashboard. In the Quick Actions or sections, find 'Invite Codes'. Click 'Generate New Code'. A unique code will appear. Share this code with the new board member — they'll enter it during registration. Each code works only once.",
    keywords: ["invite code", "board registration", "new board member", "generate code", "invite link", "registration code", "board invite"],
    roles: ["administrator"],
    denyRoles: ["member"],
    pages: ["/dashboard"],
  },
  {
    q: "How do I copy or delete an invite code?",
    a: "Go to Dashboard → Invite Codes section. Each code has a Copy button (for sharing) and a Delete button. Copied codes go to your clipboard. Delete codes that have been used or are no longer needed.",
    keywords: ["copy code", "delete code", "share code", "invite code copy", "remove code"],
    roles: ["administrator"],
    denyRoles: ["member"],
    pages: ["/dashboard"],
  },

  // ─── Settings & Profile ───
  {
    q: "How do I change my password?",
    a: "Go to Settings (gear icon in the top nav bar). Under your profile, you can update your password. You'll need to enter your current password and then your new password.",
    keywords: ["change password", "update password", "reset password", "settings", "profile", "account", "security", "login"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/dashboard/settings"],
  },
  {
    q: "How do I update my profile?",
    a: "Click on your name or the Profile link in the top navigation bar. From there you can update your display name, phone number, and other personal information. Changes save automatically.",
    keywords: ["update profile", "edit profile", "change name", "update phone", "profile settings", "my account"],
    roles: ["board_member", "administrator", "member"],
  },
  {
    q: "How do I change the theme or appearance?",
    a: "Go to Settings (gear icon in the top nav bar). Look for the Theme section. You can switch between Light, Dark, and Night modes. Your preference is saved and will persist across sessions.",
    keywords: ["theme", "dark mode", "light mode", "night mode", "appearance", "color scheme", "change color", "settings theme"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/settings"],
  },

  // ─── Newsletter ───
  {
    q: "How do I subscribe or unsubscribe from emails?",
    a: "Go to the Subscribe page from the navigation menu. You'll see two tabs: Subscribe and Unsubscribe. Enter your email and optionally your name, then click the button. Board members can also manage subscribers from Dashboard → Subscribers section.",
    keywords: ["subscribe", "unsubscribe", "email list", "newsletter", "mailing list", "email signup", "newsletter signup"],
    roles: ["board_member", "administrator", "member"],
  },
  {
    q: "How do I manage newsletter subscribers?",
    a: "Go to Dashboard → Subscribers. You can see all newsletter subscribers and their status (active/unsubscribed). You can manually unsubscribe someone if they request it, or delete their record entirely.",
    keywords: ["subscriber", "subscriber list", "email subscriber", "newsletter list", "manage subscriber"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],    pages: ["/dashboard/subscribers"],
  },

  // ─── Public Pages ───
  {
    q: "Where can I find prayer times?",
    a: "Prayer times are displayed on the homepage and the dedicated Prayer Times page. The times are fetched live from an API. Jumu'ah prayer information is also shown. Click 'View Full Monthly Schedule' for the complete monthly timetable.",
    keywords: ["prayer time", "salah", "fajr", "dhuhr", "asr", "maghrib", "isha", "jumu'ah", "namaz", "salat", "prayer schedule"],
    roles: ["board_member", "administrator", "member"],
  },
  {
    q: "How do I view the board of directors?",
    a: "Go to the Boards page from the navigation menu. You'll see all board members with their photos, titles, and contact information organized by Board of Directors and Board of Trustees sections.",
    keywords: ["board", "director", "trustee", "board member", "leadership", "board of directors", "board of trustees", "who runs mhma"],
    roles: ["board_member", "administrator", "member"],
  },
  {
    q: "How can I see masjid construction progress?",
    a: "Go to the Masjid Construction page. You'll see the fundraising progress bar, campaign stats (total raised, donor count, square footage), recent updates with photos, giving tiers, donor wall, and information about other ways to give.",
    keywords: ["masjid construction", "building progress", "fundraising", "campaign", "donor wall", "construction status", "new masjid", "islamic center"],
    roles: ["board_member", "administrator", "member"],
  },
  {
    q: "Where do I find information about programs?",
    a: "Go to the Programs page from the navigation menu. All active programs are listed there. Click on any program to see more details including description, schedule, and how to enroll.",
    keywords: ["find programs", "program list", "program page", "view programs", "program directory", "classes", "courses"],
    roles: ["board_member", "administrator", "member"],
  },

  // ─── WordPress Transition Guide ───
  {
    q: "How do I transition from WordPress to this website?",
    a: "Welcome! This new website replaces the old WordPress site. Here's what you need to know: 1) All content (events, programs, news) is now managed through Dashboard. 2) The old WordPress login no longer works. 3) Your board member account was created for you. 4) Contact info@mhma.info if you need access. Use the Dashboard to manage everything — no more WordPress admin panel needed.",
    keywords: ["wordpress", "wp", "transition", "migration", "old site", "new website", "move from wordpress", "wordpress replacement"],
    roles: ["board_member", "administrator", "member"],
  },
  {
    q: "How is this different from WordPress?",
    a: "This site is custom-built and much simpler than WordPress. Key differences: 1) No plugins to update. 2) Everything is in one Dashboard. 3) Changes are instant — no caching issues. 4) Mobile-friendly by default. 5) No separate login — use your email. 6) Add events, programs, and news directly without needing to create pages. 7) RSVPs and enrollments are handled automatically.",
    keywords: ["difference", "vs wordpress", "compared to wordpress", "new system", "custom website", "how is this different"],
    roles: ["board_member", "administrator", "member"],
  },
  {
    q: "How do I log in for the first time?",
    a: "Click 'Member Login' in the top navigation bar. Enter your email address and click 'Login'. Check your email for a magic link — click it to log in. No password needed. If you have a password set, you can also use 'Continue with Email & Password'. First-time users: use an invite code from an existing board member.",
    keywords: ["login", "sign in", "first time login", "magic link", "how to login", "access account", "board login", "sign in first time"],
    roles: ["board_member", "administrator", "member"],
  },
  {
    q: "How do I register as a new board member?",
    a: "You need an invite code from an existing administrator. Go to the Register page. Enter your name, email, phone, and the invite code. Your account will be created with board member access. If you don't have a code, contact info@mhma.info.",
    keywords: ["register", "sign up", "new account", "board registration", "create account", "invite code", "join as board"],
    roles: ["board_member", "administrator", "member"],
  },

  // ─── Dashboard Navigation Help ───
  {
    q: "How do I get to the dashboard?",
    a: "Click on 'Dashboard' in the top navigation bar (the word 'DASHBOARD' with a dropdown arrow). From there you can access all sections: Events, Programs, News, Testimonials, Construction, Donations, Pledges, Contact, Members, Analytics, and more.",
    keywords: ["go to dashboard", "dashboard link", "where is dashboard", "access dashboard", "open dashboard", "board dashboard", "admin panel"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],    pages: ["/dashboard"],
  },
  {
    q: "What is the dashboard?",
    a: "The Dashboard is the control center for board members. It shows all pending items (enrollments, RSVPs, contacts), quick action buttons for common tasks, and individual sections for managing events, programs, news, donations, and more. You can customize which sections appear using the 'Customize' button.",
    keywords: ["what is dashboard", "dashboard overview", "dashboard explain", "what can i do in dashboard", "dashboard help"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],    pages: ["/dashboard"],
  },

  // ─── Bulk Operations ───
  {
    q: "How do I approve or reject multiple items at once?",
    a: "Many sections have 'Approve All' and 'Reject All' buttons at the top. For example: Enrollments, Scheduling Requests, and RSVPs all support bulk processing. These buttons process all pending items with a single click. Use with care — there's no undo!",
    keywords: ["approve all", "reject all", "bulk approve", "bulk reject", "batch process", "approve multiple", "mass approve"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],  },
  {
    q: "How do I mark all contact submissions as read?",
    a: "Go to Dashboard → Contact & FAQ. At the top of the Contact Submissions section, there's a 'Mark All Read' button. This marks all unread submissions as read in one click.",
    keywords: ["mark all read", "mark read", "bulk read", "all read", "read all messages"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],    pages: ["/dashboard/contact-submissions"],
  },

  // ─── Security & Role Help ───
  {
    q: "Can I create events as a regular member?",
    a: "No, only board members can create events. If you're a regular member, you can submit a scheduling request from the public 'Event Scheduling Request' page, which a board member can then approve.",
    keywords: ["create event member", "regular member event", "can i create", "member permissions", "not board member"],
    roles: ["member"],
    denyRoles: ["board_member", "administrator"],
  },
  {
    q: "Can you create an event for me?",
    a: "Only board members can create events directly in the Dashboard. As a regular member, you can submit an Event Scheduling Request from the Contact menu. A board member will review and approve it. Go to the 'Event Scheduling Request' page to fill out the form.",
    keywords: ["create for me", "make event for me", "ai create event", "assistant create", "do it for me"],
    roles: ["member"],
    denyRoles: ["board_member", "administrator"],
  },
  {
    q: "What can board members do?",
    a: "Board members have full access: create/edit/delete events, programs, news, testimonials, and construction updates; approve/reject enrollments, RSVPs, and scheduling requests; manage donations, pledges, subscribers, users, and invite codes; view analytics and activity logs; and customize the dashboard layout.",
    keywords: ["board member powers", "board permissions", "what can board do", "admin abilities", "board access", "board privileges"],
    roles: ["board_member", "administrator", "member"],
  },
  {
    q: "What can regular members do?",
    a: "Regular members can: view public pages, subscribe to the newsletter, submit event scheduling requests, RSVP to events, enroll in programs, make pledges and donations, update their profile and password, and change their theme preferences.",
    keywords: ["member permissions", "regular member", "what can members do", "member access", "public features"],
    roles: ["board_member", "administrator", "member"],
  },

  // ─── Confused / Frustrated User Help ───
  {
    q: "I don't understand",
    a: "I understand this can be frustrating. Let me try again — what would you like help with? You can ask about events, programs, navigation, donations, or any dashboard feature. Tell me what you're trying to do and I'll guide you step by step.",
    keywords: ["dont understand", "don't understand", "confused", "not understand", "what do you mean", "huh", "not making sense", "im confused", "i'm confused", "what are you talking about", "this is confusing"],
    roles: ["board_member", "administrator", "member"],
  },
  {
    q: "Can you understand me?",
    a: "Yes, I can hear you! I'm a keyword-based assistant, so I match your words against my knowledge base. Try being more specific about what you need. For example: 'How do I get to the events page?' or 'Show me how to enroll in a program'.",
    keywords: ["can you understand", "do you understand", "are you listening", "hello are you there", "hello?", "you there", "are you there", "can you hear", "do you get it", "understand me"],
    roles: ["board_member", "administrator", "member"],
  },
  {
    q: "You're not helping me",
    a: "I'm sorry I'm not giving you the right answers. Let's try a different approach. Can you tell me what you're trying to do on the website? For example: 'I want to see the events page' or 'How do I sign up for a program?'",
    keywords: ["not helping", "you're not helping", "you not helping", "useless", "bad assistant", "not good", "wrong answer", "not what i asked", "not what i want", "you dont understand", "you don't get it"],
    roles: ["board_member", "administrator", "member"],
  },

  // ─── Navigation Help ───
  {
    q: "How do I get to the Events page?",
    a: "Click 'Events' in the main navigation menu. On the Events page you'll see upcoming events and a calendar. Board members can also click 'Manage Events' to go to the Dashboard events section.",
    keywords: ["go to events", "events page", "find events", "events link", "navigate to events"],
    roles: ["board_member", "administrator", "member"],
  },
  {
    q: "How do I get to the Programs page?",
    a: "Click 'Programs' in the main navigation menu. On the Programs page you'll see all active programs. Board members can also click 'Manage Programs' to go to the Dashboard programs section.",
    keywords: ["go to programs", "programs page", "find programs", "programs link", "navigate to programs"],
    roles: ["board_member", "administrator", "member"],
  },
  {
    q: "How do I get to the News page?",
    a: "Click 'News' in the main navigation menu. All published news articles are shown there. Board members can click 'Manage News' to go to the Dashboard news section.",
    keywords: ["go to news", "news page", "find news", "news link", "navigate to news"],
    roles: ["board_member", "administrator", "member"],
  },

  // ─── General MHMA Info ───
  {
    q: "What is MHMA?",
    a: "Mountain House Muslim Association (MHMA) is a 501(c)(3) nonprofit organization serving the Muslim community in Mountain House, California. We provide religious services, educational programs, and community events. Our mission is to build an Islamic Center that serves as a hub for faith, education, and community gathering.",
    keywords: ["what is mhma", "about mhma", "mhma meaning", "mountain house muslim", "organization info"],
    roles: ["board_member", "administrator", "member"],
  },
  {
    q: "Where is MHMA located?",
    a: "MHMA is located at 250 E. Main St., Mountain House, CA 95391. You can find directions on the Contact page. Currently, we hold events at rented spaces including Mountain House Community Center and various school facilities while working toward building a permanent Islamic Center.",
    keywords: ["location", "address", "where is mhma", "directions", "find us", "contact address"],
    roles: ["board_member", "administrator", "member"],
  },
  {
    q: "How can I contact MHMA?",
    a: "Email: info@mhma.info. You can also use the Contact form on the Contact page. For board members, internal communication is handled through the Dashboard and email.",
    keywords: ["contact", "email mhma", "reach mhma", "get in touch", "mhma email"],
    roles: ["board_member", "administrator", "member"],
  },
  {
    q: "How do I donate to MHMA?",
    a: "Go to the Donate page. You can make a one-time donation, set up recurring donations, or make a pledge (promise to donate later). Donations can be designated for Masjid Construction, General Fund, Zakat, or specific programs. You can also donate through the pledge system and fulfill it later.",
    keywords: ["donate", "give money", "contribute", "donation", "support", "make donation", "how to donate", "zakat", "sadaqah"],
    roles: ["board_member", "administrator", "member"],
  },
  {
    q: "How do I enroll in a program?",
    a: "Go to the Programs page and find the program you're interested in. Click on it to view details. There should be an enrollment form or link to sign up. If you're logged in, your information will be pre-filled.",
    keywords: ["enroll", "sign up", "register for program", "join class", "program enrollment", "how to enroll"],
    roles: ["board_member", "administrator", "member"],
  },
  {
    q: "How do I submit a scheduling request for an event?",
    a: "Go to the 'Event Scheduling Request' page from the navigation menu (under Contact). Fill in your event details including title, date, time, estimated attendees, and description. A board member will review and approve your request.",
    keywords: ["scheduling request", "request event", "submit request", "event request", "book event", "reserve date"],
    roles: ["board_member", "administrator", "member"],
  },
  {
    q: "How do I volunteer with MHMA?",
    a: "Go to the Volunteer page from the navigation menu (under Contact). Fill in your information, availability, and interests. A board member will review your submission and reach out to you.",
    keywords: ["volunteer", "help out", "volunteer signup", "community service", "get involved"],
    roles: ["board_member", "administrator", "member"],
  },
  {
    q: "Who am I? What is my role?",
    a: "Since you're logged in, you have access to member-specific features. If you're a board member, you'll see the Dashboard with full management tools. Regular members can access their profile, notifications, and settings. Use the navigation bar to explore what's available to you.",
    keywords: ["who am i", "my role", "my account", "my profile", "what can i do", "my permissions", "my access", "logged in", "my status", "who is logged in"],
    roles: ["board_member", "administrator", "member"],
  },
  {
    q: "How do I manage events?",
    a: "As a board member, go to Dashboard → Events to create, edit, delete events, and manage RSVPs. Non-board members can submit an Event Scheduling Request from the Contact menu for a board member to review.",
    keywords: ["manage events", "event management", "events dashboard", "control events", "handle events", "manage rsvps", "event workflow"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],
    pages: ["/dashboard/events"],
  },
  {
    q: "How do I manage programs?",
    a: "Board members use Dashboard → Programs to create, edit, delete programs, and manage enrollments. Non-board members can browse programs on the public Programs page and enroll in them.",
    keywords: ["manage programs", "program management", "programs dashboard", "control programs", "handle programs", "manage enrollments", "program workflow"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],
    pages: ["/dashboard/programs"],
  },
  {
    q: "What sections are in the Dashboard?",
    a: "The Dashboard has sections for Events, Programs, News, Testimonials, Scheduling Requests, Masjid Construction, Donations, Pledges, Activity Log, Analytics, Contact Submissions, and Members (Users). Each section has its own management tools and views. Go to Dashboard → [section name] to access each one.",
    keywords: ["dashboard sections", "dashboard overview", "what's in dashboard", "dashboard menu", "dashboard items", "dashboard tabs", "all dashboard features"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],
    pages: ["/dashboard"],
  },
  {
    q: "How do I donate or pledge?",
    a: "Go to the Donate page to make a one-time or recurring donation. You can also visit the Pledge page to make a pledge (promise to donate later) and fulfill it when you're ready. Donations can go to Masjid Construction, General Fund, Zakat, or specific programs.",
    keywords: ["donate money", "pledge donation", "make pledge", "financial contribution", "give donation", "donate to masjid", "donation options", "how to give"],
    roles: ["board_member", "administrator", "member"],
  },
  {
    q: "How do construction updates work?",
    a: "Board members can add updates with photos and progress descriptions from Dashboard → Construction. All updates are displayed on the Masjid Construction page for the community to see. Members and visitors can view the latest progress photos and descriptions there.",
    keywords: ["construction update", "masjid progress", "building status", "construction photos", "update construction", "masjid construction status", "progress report"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/masjid-construction"],
  },
  {
    q: "How do notifications work?",
    a: "If you're logged in, click the Bell icon (Notifications) in the top navigation bar to view your notifications. Board members get notified about new scheduling requests, enrollments, and contact submissions. Regular members get notified about event and program updates.",
    keywords: ["notifications", "bell icon", "notification bell", "my notifications", "alerts", "get notified", "notice", "notification settings"],
    roles: ["board_member", "administrator", "member"],
  },
  {
    q: "How do I update my profile?",
    a: "Go to the Profile page from the navigation bar. You can update your name, email, phone number, and password. For board members, additional profile fields may be available. Changes save immediately.",
    keywords: ["update profile", "edit profile", "my profile", "change password", "update name", "change email", "profile settings", "account settings"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/profile"],
  },
  {
    q: "How do I change theme or settings?",
    a: "Go to the Settings page from the navigation bar. From there you can toggle between Light, Dark, and Night themes. The theme applies across the entire site and is saved to your account if you're logged in.",
    keywords: ["change theme", "dark mode", "light mode", "night mode", "settings", "theme settings", "toggle theme", "switch theme", "appearance"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/settings"],
  },
  {
    q: "How do analytics work?",
    a: "Go to Dashboard → Analytics to view charts and stats about events, programs, users, RSVPs, donations, pledges, and more. You can filter by date range and view trends. Data is updated in real-time as new registrations and donations come in.",
    keywords: ["analytics", "statistics", "charts", "reports", "data", "insights", "dashboard analytics", "site stats", "metrics", "performance"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],
    pages: ["/dashboard/analytics"],
  },
  {
    q: "How do I manage donations?",
    a: "Go to Dashboard → Donations to view all donations, filter by designation (Masjid Construction, General, Zakat, Programs), and see donor information. You can also toggle whether donations show on the public donor wall and whether donors appear anonymous.",
    keywords: ["manage donations", "view donations", "donation list", "donor management", "donation dashboard", "donation report", "track donations"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],
    pages: ["/dashboard/donations"],
  },
  {
    q: "How do I manage pledges?",
    a: "Go to Dashboard → Pledges to view all pledges, their status (pending, fulfilled, partially fulfilled), and amounts. You can mark pledges as fulfilled when the donor completes their payment. Pledge data helps track fundraising progress.",
    keywords: ["manage pledges", "view pledges", "pledge list", "pledge management", "pledge dashboard", "fulfill pledge", "mark pledge fulfilled"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],
    pages: ["/dashboard/pledges"],
  },
  {
    q: "How do I see the activity log?",
    a: "Go to Dashboard → Activity Log to view a timeline of all actions taken on the site — events created, enrollments approved, news published, etc. You can filter by action type and date range. This helps track who did what and when.",
    keywords: ["activity log", "audit trail", "action history", "user activity", "recent actions", "activity timeline", "change log", "track changes"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],
    pages: ["/dashboard/activity"],
  },
  {
    q: "How do I manage members?",
    a: "Go to Dashboard → Members to see all registered users, their roles, registration dates, and profile information. Board members can view member details but cannot change roles or delete accounts for security reasons.",
    keywords: ["manage members", "user list", "view members", "member directory", "users", "registered users", "member management", "all members"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],
    pages: ["/dashboard/users"],
  },
  {
    q: "How do I handle contact submissions?",
    a: "Go to Dashboard → Contact Submissions to view messages sent through the Contact form. You can reply to inquiries, mark them as resolved, and manage the FAQ section. FAQ entries appear on the public FAQ page.",
    keywords: ["contact submissions", "contact form", "messages", "inquiries", "faq", "manage faq", "respond to inquiries", "contact dashboard"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],
    pages: ["/dashboard/contact-submissions"],
  },
  {
    q: "What is the role of a board member?",
    a: "As a board member, you have full access to the Dashboard for managing events, programs, news, testimonials, construction updates, donations, pledges, members, analytics, and more. You can also view the Activity Log and handle Contact Submissions. Use the Settings page to customize your experience.",
    keywords: ["board member", "board role", "board duties", "board access", "what board can do", "board permissions", "board responsibilities", "admin role"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],
  },
  {
    q: "What can a regular member do?",
    a: "As a regular member, you can manage your profile, view your notifications, change your theme/settings, browse events and programs, enroll in programs, RSVP to events, make donations and pledges, submit event scheduling requests, volunteer, and view the masjid construction page. Board-specific features (like the full Dashboard) are limited to board members.",
    keywords: ["regular member", "member role", "member features", "what members can do", "member access", "member permissions", "non board member", "volunteer member"],
    roles: ["member"],
  },
  {
    q: "What can I do if I'm not logged in?",
    a: "As a visitor, you can browse the homepage, About page, Events, Programs, News, Donate, Volunteer, Masjid Construction page, and Contact page. You can also subscribe to the newsletter and change the theme in Settings. Logging in gives you access to member features like profile management and notifications.",
    keywords: ["not logged in", "visitor", "guest", "public access", "what can guests do", "browse without login", "no account", "not registered", "public features"],
    roles: ["member"],
  },
  {
    q: "How do I RSVP to an event?",
    a: "Go to the Events page and find the event you want to attend. Click 'RSVP' and fill in your details. If you're logged in, your information will be pre-filled. Once you submit, a board member will review and approve your RSVP.",
    keywords: ["rsvp", "rsvp to event", "respond to event", "attend event", "event rsvp", "confirm attendance", "i want to go", "event response"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/events"],
  },
  {
    q: "What is the Impact Report?",
    a: "The Impact Report page shows the community impact of MHMA through key metrics like funds raised, families served, programs offered, and more. It's updated regularly to reflect the latest achievements and milestones.",
    keywords: ["impact report", "community impact", "annual report", "impact stats", "our impact", "achievements", "milestones", "community metrics"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/impact-report"],
  },
  {
    q: "How do I use the scheduling requests section?",
    a: "Board members can view and manage event scheduling requests from Dashboard → Scheduling. Each request shows the submitter's details, event info, and status. You can approve or reject requests. Approved requests can be turned into actual events.",
    keywords: ["scheduling requests", "event scheduling", "approve scheduling", "reject scheduling", "manage requests", "scheduling dashboard", "pending requests"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],
    pages: ["/dashboard/scheduling-requests"],
  },
  {
    q: "How do I manage membership profiles?",
    a: "Board members can view all registered members from Dashboard → Members. You can see their email, role, registration date, and last login. You can also update member roles or remove members if needed.",
    keywords: ["manage members", "member list", "users list", "view members", "member profiles", "edit member", "delete member", "member role", "all members", "registered users"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],
    pages: ["/dashboard/users"],
  },
  {
    q: "How do I approve or reject enrollments?",
    a: "Go to Dashboard → Programs. You'll see pending enrollments that need review. Click Approve to accept a member into the program, or Reject to decline. Approved members will be notified automatically.",
    keywords: ["approve enrollment", "reject enrollment", "pending enrollment", "program enrollment", "manage enrollments", "review enrollments", "accept enrollment", "deny enrollment"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],
    pages: ["/dashboard/programs"],
  },
  {
    q: "How do I manage volunteers?",
    a: "Board members can view volunteer sign-ups from the Volunteers page. You can see who has signed up, their contact info, and areas of interest. Use this to coordinate volunteer efforts.",
    keywords: ["volunteer", "volunteers", "manage volunteers", "volunteer list", "volunteer signup", "volunteer management", "view volunteers", "volunteer coordinator"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],
    pages: ["/volunteer"],
  },
  {
    q: "How do I view analytics?",
    a: "Go to Dashboard → Analytics to see site usage statistics, including page views, active users, popular pages, and engagement metrics. Data is updated in real time.",
    keywords: ["analytics", "statistics", "site stats", "page views", "usage stats", "traffic", "engagement", "analytics dashboard", "view analytics", "metrics"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],
    pages: ["/dashboard/analytics"],
  },
  {
    q: "How do I create and manage pledges?",
    a: "Go to Dashboard → Pledges to view all pledges made by community members. You can add new pledges, update pledge amounts, mark pledges as fulfilled, or remove them. Pledges are shown on the Pledge and Masjid Construction pages.",
    keywords: ["pledge", "pledges", "manage pledges", "create pledge", "add pledge", "pledge amount", "fulfill pledge", "pledge management", "new pledge", "donation pledge"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],
    pages: ["/dashboard/pledges"],
  },
  {
    q: "How do I contact the board?",
    a: "You can reach the board by filling out the Contact form on the Contact page. Select 'Board Inquiry' as the subject. Your message will be sent to the board members for review.",
    keywords: ["contact board", "message board", "email board", "reach board", "board contact", "board inquiry", "talk to board", "ask board", "contact mhma board"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/contact"],
  },
  {
    q: "Where can I find prayer times?",
    a: "Prayer times are displayed on the homepage under the Prayer Times section. You can also visit the Prayer Times page for the full daily schedule with Fajr, Dhuhr, Asr, Maghrib, and Isha times.",
    keywords: ["prayer times", "salah times", "namaz times", "prayer schedule", "daily prayer", "fajr", "dhuhr", "asr", "maghrib", "isha", "prayer timings", "when to pray"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/prayer-times"],
  },
  {
    q: "How do I donate to MHMA?",
    a: "Go to the Donate page to make a donation. You can choose from various funds including Masjid Construction, Programs, Zakat, General, and Other. Enter your donation amount and complete the payment. Your donation will be recorded in the system.",
    keywords: ["donate", "donation", "make donation", "give money", "contribute", "financial support", "donate online", "support mhma", "give donation", "fund donation", "pay donation"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/donate"],
  },
  {
    q: "How do I view my profile?",
    a: "Click on PROFILE in the top navigation bar to view your profile. Here you can see your name, email, role, and registration date. You can update your display name and other settings.",
    keywords: ["my profile", "view profile", "edit profile", "profile page", "account info", "my account", "update profile", "profile settings", "user profile", "see profile"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/profile"],
  },
  {
    q: "How do I view the activity log?",
    a: "Board members can view the activity log from Dashboard → Activity Log. This shows all recent actions taken on the site, such as event creation, edits, member changes, and other administrative actions.",
    keywords: ["activity log", "recent activity", "audit log", "action log", "history", "changes log", "site activity", "view activity", "what changed", "activity history"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],
    pages: ["/dashboard/activity"],
  },
  {
    q: "How do I manage testimonials?",
    a: "Go to Dashboard → Testimonials to view, add, edit, or delete testimonials. Testimonials appear on the homepage and help showcase community feedback. You can approve pending testimonials before they go live.",
    keywords: ["testimonial", "testimonials", "manage testimonials", "add testimonial", "edit testimonial", "delete testimonial", "community feedback", "review testimonial", "approve testimonial"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],
    pages: ["/dashboard/testimonials"],
  },
  {
    q: "How do I use the Builders Club?",
    a: "The Builders Club is a recurring donation program for the Masjid Construction fund. Visit the Builders Club page to sign up for monthly contributions. Board members can view and manage Builders Club members from the dashboard.",
    keywords: ["builders club", "builder club", "monthly donation", "recurring donation", "construction club", "masjid builders", "builders club signup", "builders club members"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/builders-club"],
  },
  {
    q: "How do I manage the Masjid Construction page?",
    a: "Board members can update the Masjid Construction page from Dashboard → Construction. Add progress updates, change the fundraising goal, update the raised amount, and add new photos of the construction progress.",
    keywords: ["masjid construction", "construction updates", "update construction", "construction progress", "masjid building", "construction dashboard", "fundraising goal", "construction photos", "edit construction"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],
    pages: ["/dashboard/masjid-construction"],
  },
  {
    q: "Can non-board members create events?",
    a: "Only board members can create events directly. As a regular member, you can submit an Event Scheduling Request from the Contact page. A board member will review and approve it.",
    keywords: ["non board member event", "create event as member", "regular member event", "not board create event", "member create event", "event request member", "submit event request"],
    roles: ["member"],
    denyRoles: ["board_member", "administrator"],
    pages: ["/event-scheduling-request"],
  },
  {
    q: "How do I view my notification history?",
    a: "Click on NOTIFICATIONS in the top navigation bar to view your notifications. This shows recent alerts about events, programs, enrollments, and other important updates. The red badge shows unread notifications.",
    keywords: ["notifications", "my notifications", "view notifications", "notification history", "recent alerts", "check notifications", "see notifications", "notification badge", "clear notifications"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/dashboard/notifications"],
  },
  {
    q: "How do I submit a testimonial?",
    a: "You can submit a testimonial by contacting MHMA through the Contact page. Select 'Testimonial' as the subject and share your experience. Board members will review and publish it on the website.",
    keywords: ["submit testimonial", "share experience", "give feedback", "write testimonial", "add testimonial", "leave review", "community feedback", "share story"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/contact"],
  },
  {
    q: "How do I subscribe or unsubscribe from the newsletter?",
    a: "Go to the Subscribe page. Enter your email to subscribe to the MHMA newsletter. To unsubscribe, enter your email and click the unsubscribe option. You'll receive updates about events, programs, and community news.",
    keywords: ["subscribe", "unsubscribe", "newsletter", "email updates", "subscribe newsletter", "unsubscribe newsletter", "email subscription", "mailing list", "newsletter signup"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/subscribe"],
  },
  {
    q: "What is the Community Transparency page?",
    a: "The Community Transparency page provides financial and operational transparency for MHMA. It shows how funds are used, board decisions, and community initiatives. You can find it under the About section.",
    keywords: ["community transparency", "transparency", "financial transparency", "openness", "how funds used", "transparency report", "community transparency page", "transparent operations"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/community-transparency"],
  },
  {
    q: "What committees does MHMA have?",
    a: "MHMA has various committees including the Education Committee, Events Committee, Finance Committee, and Outreach Committee. Visit the Committees page under About to learn more about each committee and how to get involved.",
    keywords: ["committees", "committee", "education committee", "events committee", "finance committee", "outreach committee", "join committee", "committee members", "committee information"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/committees"],
  },
  {
    q: "How do I contact the MHMA board members?",
    a: "Visit the Board page under About to see the current board members, their roles, and contact information. You can also use the Contact form to send a message to the board.",
    keywords: ["board members", "who is on the board", "board of directors", "board list", "board contact info", "board directory", "current board", "board leadership", "mhma board"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/board"],
  },
  {
    q: "How do I enroll in programs?",
    a: "Visit the Programs page and browse available programs. Click 'Enroll Now' on any program you're interested in. Fill in the enrollment form with your details and submit. A board member will review and approve your enrollment.",
    keywords: ["enroll", "enrollment", "join program", "sign up program", "program enrollment", "register program", "class enrollment", "program signup", "enroll now"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/enroll"],
  },
  {
    q: "How do I pay Zakat?",
    a: "You can pay your Zakat through the Zakat page. Enter the amount you wish to give and complete the payment. Your Zakat contribution will be recorded and used for community programs. Visit the Donate page and select 'Zakat' as the fund.",
    keywords: ["zakat", "pay zakat", "zakat donation", "zakat calculation", "give zakat", "zakat fund", "zakat payment", "islamic charity", "obligatory charity"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/zakat"],
  },
  {
    q: "Go to events page",
    a: "You can view all upcoming events on the Events page. Click the EVENTS link in the navigation menu or visit /events to see the full list. From there you can RSVP and get event details.",
    keywords: ["go to events", "events page", "navigate events", "open events", "show events", "take me to events", "events link", "find events page", "event navigation", "where is events page"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/events"],
  },
  {
    q: "Go to dashboard",
    a: "Click DASHBOARD in the top navigation bar to access the admin dashboard. From there you can manage events, programs, news, donations, members, and more.",
    keywords: ["go to dashboard", "open dashboard", "navigate dashboard", "take me to dashboard", "dashboard link", "show dashboard", "dashboard navigation", "admin panel"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],
    pages: ["/dashboard"],
  },
  {
    q: "Go to programs page",
    a: "Click PROGRAMS in the navigation menu to visit the Programs page. You'll find all available programs and classes. Click on any program for details or to enroll.",
    keywords: ["go to programs", "programs page", "open programs", "show programs", "take me to programs", "programs link", "navigate programs", "find programs"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/programs"],
  },
  {
    q: "Go to donate page",
    a: "Click DONATE in the navigation menu. You can choose from Masjid Construction, Programs, Zakat, General, or Other funds. Every contribution helps the community.",
    keywords: ["go to donate", "donate page", "open donate", "take me to donate", "donation page", "show donate", "donate link", "navigate donate", "where to donate"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/donate"],
  },
  {
    q: "Go to settings",
    a: "Click SETTINGS in the top navigation bar. From Settings you can change your theme (Light, Dark, or Night), update preferences, and manage your account settings.",
    keywords: ["go to settings", "settings page", "open settings", "take me to settings", "settings link", "show settings", "navigate settings", "theme settings", "account settings"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/settings"],
  },
  // ─── Navigation / Go-to queries ───
  {
    q: "Go to the homepage",
    a: "Click the MHMA logo in the top left to return to the homepage. You can also click HOME in the navigation menu.",
    keywords: ["go to home", "homepage", "back to home", "main page", "home page", "go home", "return home", "home link"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/"],
  },
  {
    q: "Go to the About page",
    a: "Click ABOUT in the navigation menu. From About you can learn about MHMA's history, board, committees, and bylaws.",
    keywords: ["go to about", "about page", "about mhma", "about us", "organization info", "learn about", "about link", "navigate about"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/about"],
  },
  {
    q: "Go to the Contact page",
    a: "Click CONTACT in the navigation menu. From Contact you can send a message, find our address, and access FAQ, newsletter subscription, and volunteer signup.",
    keywords: ["go to contact", "contact page", "contact us", "reach us", "contact form", "get in touch", "contact mhma", "contact link"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/contact"],
  },
  {
    q: "Go to the FAQ page",
    a: "Go to Contact → FAQ from the navigation menu. Frequently asked questions about MHMA, membership, events, donations, and more are answered there.",
    keywords: ["go to faq", "faq page", "frequently asked questions", "help page", "common questions", "faq link", "open faq", "navigate faq"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/contact/faq"],
  },
  {
    q: "Go to the volunteer page",
    a: "Go to Contact → Volunteer from the navigation menu. Sign up to volunteer your time and skills for MHMA events and programs.",
    keywords: ["go to volunteer", "volunteer page", "volunteer signup", "volunteer now", "volunteer opportunities", "volunteer link", "help out", "community service"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/volunteer"],
  },
  {
    q: "Go to the subscribe page",
    a: "Go to Contact → Subscribe / Unsubscribe from the navigation menu. You can sign up for the newsletter or manage your email preferences.",
    keywords: ["go to subscribe", "subscribe page", "newsletter signup", "email list", "mailing list", "subscribe link", "newsletter page", "manage subscription"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/subscribe"],
  },
  {
    q: "Go to the RSVP page",
    a: "Go to Events → RSVP from the navigation menu. You can RSVP for upcoming events there.",
    keywords: ["go to rsvp", "rsvp page", "rsvp link", "open rsvp", "rsvp to events", "navigate rsvp", "rsvp form", "respond to event"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/rsvp"],
  },
  {
    q: "Go to the enrollment page",
    a: "Go to Programs → Enroll Now from the navigation menu. Browse available programs and enroll online.",
    keywords: ["go to enroll", "enrollment page", "enroll now", "program signup", "enroll link", "open enrollment", "navigate enroll", "register for program"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/enroll"],
  },
  {
    q: "Go to the Zakat page",
    a: "Go to Programs → Zakat from the navigation menu. You can pay your Zakat contribution online.",
    keywords: ["go to zakat", "zakat page", "zakat link", "pay zakat", "zakat donation", "zakat form", "open zakat", "navigate zakat"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/zakat"],
  },
  {
    q: "Go to the Masjid Construction page",
    a: "Go to Donate → Masjid Construction from the navigation menu. See construction progress, fundraising goals, and make a donation.",
    keywords: ["go to masjid construction", "construction page", "masjid building", "construction link", "open construction", "navigate construction", "masjid construction link", "building project"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/masjid-construction"],
  },
  {
    q: "Go to the Pledge page",
    a: "Go to Donate → Pledge from the navigation menu. You can make a pledge to support MHMA's initiatives.",
    keywords: ["go to pledge", "pledge page", "make a pledge", "pledge link", "open pledge", "navigate pledge", "pledge form", "pledge donation"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/pledge"],
  },
  {
    q: "Go to the Builders Club page",
    a: "Go to Donate → Builders Club from the navigation menu. Join the Builders Club with a recurring monthly donation for the Masjid Construction fund.",
    keywords: ["go to builders club", "builders club page", "builders club link", "open builders club", "navigate builders club", "join builders club", "monthly donation"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/builders-club"],
  },
  {
    q: "Go to the Impact Report page",
    a: "Go to Donate → Impact Report from the navigation menu. See MHMA's community impact through key metrics and achievements.",
    keywords: ["go to impact report", "impact report page", "impact link", "open impact report", "navigate impact report", "community impact", "annual report"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/impact-report"],
  },
  {
    q: "Go to the Board page",
    a: "Go to About → Board from the navigation menu. See the current board members, their roles, and contact information.",
    keywords: ["go to board", "board page", "board of directors", "board members", "board link", "open board", "navigate board", "mhma leadership"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/board"],
  },
  {
    q: "Go to the Committees page",
    a: "Go to About → Committees from the navigation menu. Learn about MHMA's committees and how to get involved.",
    keywords: ["go to committees", "committees page", "committee link", "open committees", "navigate committees", "join committee", "mhma committees"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/committees"],
  },
  {
    q: "Go to News",
    a: "Go to About → News from the navigation menu. Read the latest news and announcements from MHMA.",
    keywords: ["go to news", "news page", "news link", "open news", "navigate news", "latest news", "announcements", "mhma news"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/news"],
  },
  {
    q: "Go to the Bylaws page",
    a: "Go to About → Bylaws from the navigation menu. Read MHMA's official bylaws and governing documents.",
    keywords: ["go to bylaws", "bylaws page", "bylaws link", "open bylaws", "navigate bylaws", "constitution", "governing documents", "mhma bylaws"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/bylaws"],
  },
  {
    q: "Go to the Community Transparency page",
    a: "Go to About → Community Transparency from the navigation menu. See how MHMA operates with transparency in finances and decision-making.",
    keywords: ["go to transparency", "transparency page", "community transparency", "open transparency", "navigate transparency", "financial transparency", "mhma transparency"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/community-transparency"],
  },
  // ─── Feature-Specific Queries ───
  {
    q: "How do I change my password?",
    a: "Go to SETTINGS in the top navigation bar. From Settings you can change your password by entering your current password and a new password. Click Save to update.",
    keywords: ["change password", "update password", "reset password", "new password", "forgot password", "password change", "password settings", "account security"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/settings"],
  },
  {
    q: "How do I manage contact submissions?",
    a: "Board members can view and manage contact form submissions from Dashboard → Contact & FAQ. Each submission shows the sender's name, email, subject, and message. You can mark them as read or delete them.",
    keywords: ["contact submissions", "manage contacts", "contact form", "view submissions", "contact messages", "contact inquiries", "submission management", "contact dashboard"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],
    pages: ["/dashboard/contact-submissions"],
  },
  {
    q: "How do I approve member registrations?",
    a: "New member registrations are automatically approved. Board members can view all registered members from Dashboard → Members and update their roles or access permissions as needed.",
    keywords: ["approve member", "member registration", "new member", "member approval", "register member", "member signup", "member access", "user approval"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],
    pages: ["/dashboard/users"],
  },
  {
    q: "How do I update member roles?",
    a: "Board members can update member roles from Dashboard → Members. Find the member and click Edit. You can change their role between Member, Board Member, or Administrator. Save your changes.",
    keywords: ["update role", "member role", "change role", "edit member role", "role management", "assign role", "board role", "member permissions", "user role"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],
    pages: ["/dashboard/users"],
  },
  {
    q: "How do I delete a member?",
    a: "Board members can remove a member from Dashboard → Members. Find the member and click Delete. This will permanently remove their account and access. Use with caution.",
    keywords: ["delete member", "remove member", "delete user", "remove user", "delete account", "remove account", "member removal", "user deletion"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],
    pages: ["/dashboard/users"],
  },
  {
    q: "How do I view donation reports?",
    a: "Board members can view donation reports from Dashboard → Donations. See all donations with donor names, amounts, dates, and fund allocation. You can filter by fund type or date range.",
    keywords: ["donation report", "donation history", "view donations", "donation list", "fund report", "donation records", "donation dashboard", "financial report"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],
    pages: ["/dashboard/donations"],
  },
  {
    q: "How do I add a news article?",
    a: "Go to Dashboard → News. Click 'Add News' and fill in the title, content, and optional image. Click Save to publish. The article will appear on the News page and homepage.",
    keywords: ["add news", "create news", "news article", "write news", "publish news", "news post", "new article", "news creation", "news dashboard"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],
    pages: ["/dashboard/news"],
  },
  {
    q: "How do I edit a news article?",
    a: "Go to Dashboard → News. Find the article in the list and click Edit. Update the title, content, or image as needed. Click Save to update the article.",
    keywords: ["edit news", "update news", "modify article", "edit article", "news edit", "change news", "update article", "news update"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],
    pages: ["/dashboard/news"],
  },
  {
    q: "How do I delete a news article?",
    a: "Go to Dashboard → News. Find the article and click the Delete icon. Confirm the deletion. The article will be permanently removed.",
    keywords: ["delete news", "remove news", "delete article", "remove article", "news deletion", "remove post", "delete post", "news removal"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],
    pages: ["/dashboard/news"],
  },
  {
    q: "How do I manage programs?",
    a: "Go to Dashboard → Programs to view, add, edit, or delete programs. Each program can have a title, description, schedule, instructor, and enrollment capacity. Approved programs appear on the public Programs page.",
    keywords: ["manage programs", "program management", "add program", "edit program", "delete program", "program dashboard", "program list", "program admin"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],
    pages: ["/dashboard/programs"],
  },
  {
    q: "How do I track pledges?",
    a: "Go to Dashboard → Pledges. You can see all pledges with the pledger's name, amount, date, and status (pending, fulfilled, or cancelled). You can mark pledges as fulfilled when payment is received.",
    keywords: ["track pledge", "pledge status", "pledge tracking", "view pledges", "pledge report", "pledge management", "pledge fulfillment", "monitor pledges"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],
    pages: ["/dashboard/pledges"],
  },
  {
    q: "How do I manage event RSVPs?",
    a: "Board members can view and manage RSVPs from the event page or Dashboard → Events. Each RSVP shows the attendee's name, email, and status. You can approve or decline RSVPs.",
    keywords: ["manage rsvp", "rsvp management", "view rsvps", "rsvp list", "event rsvp", "rsvp approval", "approve rsvp", "decline rsvp", "attendee list"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],
    pages: ["/dashboard/events"],
  },
  {
    q: "How do I view past events?",
    a: "Go to Dashboard → Events. Past events are shown in the event list with their status marked as 'Past'. You can click on any past event to view details or edit them.",
    keywords: ["past events", "previous events", "old events", "event history", "view past events", "archived events", "completed events", "event archive"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],
    pages: ["/dashboard/events"],
  },
  {
    q: "How do I add an image to an event?",
    a: "When creating or editing an event in Dashboard → Events, you'll see an image upload field. Click to select an image from your computer. Supported formats are JPG, PNG, and WebP.",
    keywords: ["event image", "add image", "upload image", "event photo", "picture event", "event thumbnail", "image upload", "event media", "add photo"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],
    pages: ["/dashboard/events"],
  },
  {
    q: "How do I duplicate an event?",
    a: "There is no direct duplicate feature. You can create a new event based on an existing one by opening the event details and copying the information to a new event form.",
    keywords: ["duplicate event", "copy event", "clone event", "repeat event", "replicate event", "copy to new", "event template"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],
    pages: ["/dashboard/events"],
  },
  {
    q: "How do I change my display name?",
    a: "Go to PROFILE in the top navigation bar. You can edit your display name in the profile form. Click Save to update. Your display name will appear in the welcome message and profile.",
    keywords: ["change name", "display name", "edit name", "update name", "change display name", "profile name", "my name", "rename", "name settings"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/profile"],
  },
  {
    q: "How do I view my donations?",
    a: "Your donation history is shown on your PROFILE page. You can see the amount, date, and fund for each donation you've made.",
    keywords: ["my donations", "my giving", "donation history", "view my donations", "my contributions", "donation record", "my gifts", "personal donations"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/profile"],
  },
  {
    q: "How do I see my RSVPs?",
    a: "Your RSVPs are shown on your PROFILE page. You can see which events you've RSVP'd for and the status of each RSVP (pending, approved, or declined).",
    keywords: ["my rsvps", "my responses", "view rsvps", "rsvp history", "my events", "event responses", "attending events", "my upcoming events"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/profile"],
  },
  {
    q: "How do I view my enrollments?",
    a: "Your program enrollments are shown on your PROFILE page. See which programs you're enrolled in and their status.",
    keywords: ["my enrollments", "my programs", "enrolled programs", "program enrollments", "my classes", "registered programs", "view enrollments", "enrollment status"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/profile"],
  },
  {
    q: "How do I withdraw from a program?",
    a: "Go to your PROFILE page, find the program enrollment you want to withdraw from, and click Withdraw. Your enrollment will be cancelled and the spot will be available for others.",
    keywords: ["withdraw program", "unenroll", "cancel enrollment", "leave program", "drop program", "remove enrollment", "program withdrawal", "quit program"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/profile"],
  },
  {
    q: "How do I cancel an RSVP?",
    a: "Go to your PROFILE page, find the event RSVP you want to cancel, and click Cancel. Your RSVP will be removed and the spot will be available.",
    keywords: ["cancel rsvp", "remove rsvp", "unrsvp", "decline event", "cancel attendance", "rsvp cancellation", "change rsvp", "event cancellation"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/profile"],
  },
  {
    q: "How do I get directions to MHMA?",
    a: "Go to the Contact page and click the address link or find the Directions section. MHMA is located at 250 E. Main St., Mountain House, CA 95391. You can use Google Maps or your preferred navigation app.",
    keywords: ["directions", "map", "address", "location", "how to get there", "driving directions", "find us", "mhma location", "come to mhma", "visit mhma"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/contact#directions"],
  },
  {
    q: "How do I follow MHMA on social media?",
    a: "MHMA is on Instagram (@mhma.ig) and YouTube (@mhmuslimassociation). Links are in the top navigation bar. Follow us for updates, event highlights, and community content.",
    keywords: ["social media", "instagram", "youtube", "follow mhma", "social links", "facebook", "twitter", "social", "media", "mhma social"],
    roles: ["board_member", "administrator", "member"],
  },
  {
    q: "How do I report a bug or issue?",
    a: "Please report any bugs or issues using the Contact form on the Contact page. Select 'Technical Issue' as the subject and describe the problem in detail. The board will review and address it.",
    keywords: ["report bug", "report issue", "technical problem", "website error", "bug report", "site issue", "something broken", "error report", "glitch", "problem with site"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/contact"],
  },
  {
    q: "What is the builders club?",
    a: "The Builders Club is a recurring monthly donation program for the Masjid Construction fund. Members commit to a monthly contribution and receive exclusive updates on construction progress. Join from the Builders Club page.",
    keywords: ["builders club", "what is builders club", "monthly donation club", "recurring giving", "construction club", "builders club info", "join builders club", "monthly donor"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/builders-club"],
  },
  {
    q: "How do I become a board member?",
    a: "Board member positions are filled through elections and appointments. If you're interested in serving on the board, contact the current board through the Contact form or attend MHMA meetings to express your interest.",
    keywords: ["become board member", "join board", "board election", "board appointment", "serve on board", "board position", "board nomination", "run for board"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/contact"],
  },
  {
    q: "How do I volunteer for an event?",
    a: "Go to the Volunteer page or look for volunteer signup options on specific event pages. Fill in your details and areas of interest. The board will contact you with opportunities.",
    keywords: ["volunteer event", "event volunteer", "help at event", "volunteer opportunity", "sign up volunteer", "volunteer work", "event help", "volunteer for program"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/volunteer"],
  },
  {
    q: "Can I make a donation in someone's name?",
    a: "Yes, when making a donation on the Donate page, you can enter a tribute or memorial name in the donation notes. The donation will be recorded with the tribute information.",
    keywords: ["donation in honor", "donation in memory", "tribute donation", "memorial donation", "honor donation", "gift donation", "donate in name", "tribute gift"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/donate"],
  },
  {
    q: "Are donations tax deductible?",
    a: "MHMA is a nonprofit organization. Donations may be tax deductible. You will receive a donation receipt via email that you can use for tax purposes. Consult your tax advisor for specific advice.",
    keywords: ["tax deductible", "tax receipt", "donation receipt", "tax exempt", "nonprofit donation", "charitable donation", "tax write off", "deduction"],
    roles: ["board_member", "administrator", "member"],
  },
  {
    q: "How do I get a donation receipt?",
    a: "After making a donation, a receipt is automatically sent to your email. You can also view your donation history on your PROFILE page and download receipts from there.",
    keywords: ["donation receipt", "receipt", "tax receipt", "donation proof", "payment receipt", "get receipt", "download receipt", "email receipt", "print receipt"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/profile"],
  },
  {
    q: "What payment methods are accepted?",
    a: "MHMA accepts credit/debit cards (Visa, Mastercard, American Express, Discover) for donations and payments. All transactions are processed securely.",
    keywords: ["payment methods", "credit card", "debit card", "payment options", "pay online", "how to pay", "accepted cards", "pay by card", "secure payment"],
    roles: ["board_member", "administrator", "member"],
  },
  {
    q: "How do I contact technical support?",
    a: "For technical support, use the Contact form on the Contact page and select 'Technical Issue' as the subject. Describe your issue in detail and include any error messages you're seeing.",
    keywords: ["technical support", "tech support", "help desk", "support request", "need help", "site help", "technical help", "support ticket", "help me"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/contact"],
  },
  {
    q: "What does the dashboard include?",
    a: "The Dashboard has two main sections: Content (News, Programs, Events, Testimonials, Scheduling) and Financial (Construction, Donations, Pledges), plus Administration (Activity Log, Analytics, Contact & FAQ, Members). Each section lets you manage that aspect of the site.",
    keywords: ["dashboard overview", "dashboard sections", "what's in dashboard", "dashboard features", "dashboard content", "dashboard admin", "dashboard categories", "dashboard layout"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],
    pages: ["/dashboard"],
  },
  {
    q: "How do I filter or search for events?",
    a: "On the Events page, you can use the search bar to find events by keyword. You can also filter by date range or category if available. On the Dashboard → Events page, board members can sort by status, date, or title.",
    keywords: ["search events", "filter events", "find event", "event search", "event filter", "search bar", "search by date", "look up event", "locate event"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/events"],
  },
  {
    q: "How do I manage scheduling requests as a board member?",
    a: "Go to Dashboard → Scheduling to view all event scheduling requests from community members. Each request shows the submitter's info, proposed event details, and current status. You can approve, reject, or request more information. Approved requests can be converted to actual events.",
    keywords: ["scheduling management", "manage scheduling", "scheduling dashboard", "approve schedule", "reject schedule", "scheduling requests", "event scheduling board", "schedule review"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],
    pages: ["/dashboard/scheduling-requests"],
  },
  {
    q: "How does the AI assistant work?",
    a: "The AI assistant uses keyword matching to find answers from the MHMA knowledge base. It can answer questions about dashboard features, events, programs, donations, members, and navigation. Type your question and I'll find the best answer. Follow-up questions will remember the context of our conversation.",
    keywords: ["how ai works", "ai assistant info", "assistant help", "about this bot", "how do you work", "what can you do", "assistant features", "ai capabilities", "what do you know"],
    roles: ["board_member", "administrator", "member"],
  },
  {
    q: "What can the AI assistant do?",
    a: "I can answer questions about MHMA's website, dashboard features, navigation, events, programs, donations, members, and more. I can also guide you to specific pages on the site. Try asking me 'How do I create an event?' or 'Go to the programs page'.",
    keywords: ["what can you do", "assistant capabilities", "ai help", "bot help", "features ai", "ask you anything", "what questions", "helpful questions"],
    roles: ["board_member", "administrator", "member"],
  },
  {
    q: "How do I access member-only features?",
    a: "Log in with your member account to access member-only features including PROFILE, NOTIFICATIONS, and SETTINGS in the top navigation bar. Board members get additional access to DASHBOARD for site management.",
    keywords: ["member features", "member access", "logged in features", "member benefits", "member only", "premium features", "member perks", "member dashboard"],
    roles: ["board_member", "administrator", "member"],
  },
  {
    q: "How do I update my email address?",
    a: "Go to SETTINGS in the top navigation bar. You can update your email address in the settings form. A verification email will be sent to confirm the change.",
    keywords: ["update email", "change email", "email address", "new email", "edit email", "email settings", "my email", "modify email", "email update"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/settings"],
  },
  {
    q: "How do I delete my account?",
    a: "Account deletion can be requested by contacting the board through the Contact form. Select 'Account Deletion' as the subject and include your request. A board member will process it.",
    keywords: ["delete account", "remove account", "close account", "cancel membership", "account removal", "deactivate", "unregister", "leave mhma", "account deletion"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/contact"],
  },
  {
    q: "How do I help with the masjid construction?",
    a: "You can contribute to the Masjid Construction fund through the Donate page (select Masjid Construction), make a pledge on the Pledge page, join the Builders Club for monthly donations, or volunteer your skills. Every contribution helps!",
    keywords: ["help construction", "support masjid", "contribute construction", "masjid fund", "building fund", "construction help", "donate construction", "masjid support"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/masjid-construction"],
  },
  {
    q: "How do I suggest a new program?",
    a: "Use the Contact form to suggest a new program. Select 'Program Suggestion' as the subject and describe your idea in detail. The board will review your suggestion.",
    keywords: ["suggest program", "new program idea", "propose program", "program suggestion", "start a program", "create program idea", "recommend program", "program feedback"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/contact"],
  },
  {
    q: "How do I see upcoming events?",
    a: "Go to the Events page by clicking EVENTS in the navigation menu. Upcoming events are displayed with their date, time, and location. You can click on any event for more details and to RSVP.",
    keywords: ["upcoming events", "future events", "coming events", "events coming up", "next events", "event schedule", "events calendar", "what's happening", "upcoming activities"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/events"],
  },
  {
    q: "How do I register for a program?",
    a: "Go to the Programs page and find the program you're interested in. Click 'Enroll Now' and fill in the enrollment form. Your enrollment will be reviewed by a board member.",
    keywords: ["register program", "program registration", "sign up program", "join program", "enroll program", "program signup", "register class", "program enrollment"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/enroll"],
  },
  {
    q: "What programs does MHMA offer?",
    a: "MHMA offers various programs including educational classes, youth programs, community events, and religious study groups. Visit the Programs page for the full list with descriptions and schedules.",
    keywords: ["programs offered", "available programs", "list programs", "program types", "educational programs", "youth programs", "community programs", "current programs"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/programs"],
  },
  {
    q: "What is the Activity Log?",
    a: "The Activity Log in Dashboard → Activity Log records all significant actions taken on the site such as event creation, member updates, content changes, and administrative actions. Board members can review this for accountability and tracking.",
    keywords: ["activity log info", "what is activity log", "audit trail", "change log", "action log", "site history", "activity tracking", "admin log"],
    roles: ["board_member", "administrator"],
    denyRoles: ["member"],
    pages: ["/dashboard/activity"],
  },
  {
    q: "How do I ensure my data is private?",
    a: "Your personal data is protected and only visible to you and board members for administrative purposes. You can update your privacy settings in SETTINGS. For specific privacy concerns, contact the board.",
    keywords: ["data privacy", "privacy", "my data", "private info", "data protection", "personal data", "privacy settings", "secure data", "data safety"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/settings"],
  },
  {
    q: "What is the theme toggle?",
    a: "Go to SETTINGS to change your theme. Choose from Light (cream background, green accents), Dark (dark backgrounds with light text), or Night (darker, reduced blue light). Changes apply instantly and are saved to your account.",
    keywords: ["theme toggle", "change theme", "dark mode", "light mode", "night mode", "theme settings", "color theme", "appearance", "switch theme", "dark theme"],
    roles: ["board_member", "administrator", "member"],
    pages: ["/settings"],
  },
  {
    q: "Can I use the website on my phone?",
    a: "Yes! The MHMA website is fully responsive and works on mobile phones, tablets, and desktop computers. The layout adjusts automatically for smaller screens. The AI assistant also works on mobile.",
    keywords: ["mobile", "phone", "tablet", "mobile friendly", "responsive", "mobile view", "phone access", "mobile browser", "mobile website", "mobile support"],
    roles: ["board_member", "administrator", "member"],
  },
];
